import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-h0-xpos.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-h0-xvel.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-h0-spin.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-h0-energies.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-h0-all.png',dpi=300,bbox_inches='tight', pad_inches=0.0)


img1=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-xpos.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-xvel.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-spin.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-energies.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-h1-all.png',dpi=300,bbox_inches='tight', pad_inches=0.0)

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-xpos-zoom.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-xvel-zoom.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-spin-zoom.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-h1-energies-zoom.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-h1-all-zoom.png',dpi=300,bbox_inches='tight', pad_inches=0.0)

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-xpos.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-xvel.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-spin.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-energies.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-h2-all.png',dpi=300,bbox_inches='tight', pad_inches=0.0)

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-xpos-zoom.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-xvel-zoom.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-spin-zoom.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-h2-energies-zoom.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-h2-all-zoom.png',dpi=300,bbox_inches='tight', pad_inches=0.0)

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-i1-xpos.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-i1-xvel.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-i1-spin.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-i1-energies.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-i1-all.png',dpi=300,bbox_inches='tight', pad_inches=0.0)

img1=mpimg.imread('p2d-cmrrlinear-flatsurface-i2-xpos.png')
img2=mpimg.imread('p2d-cmrrlinear-flatsurface-i2-xvel.png')
img3=mpimg.imread('p2d-cmrrlinear-flatsurface-i2-spin.png')
img4=mpimg.imread('p2d-cmrrlinear-flatsurface-i2-energies.png')

plt.close('all')
f, ((ax1, ax2),(ax3, ax4)) = plt.subplots(2, 2)
ax1.imshow(img1)
ax1.set_axis_off()
ax2.imshow(img2)
ax2.set_axis_off()
ax3.imshow(img3)
ax3.set_axis_off()
ax4.imshow(img4)
ax4.set_axis_off()
f.subplots_adjust(left=0.01, bottom=0.01, right=0.99, top=0.99, wspace=0.01, hspace=0.01)
plt.savefig('p2d-cmrrlinear-flatsurface-i2-all.png',dpi=300,bbox_inches='tight', pad_inches=0.0)
plt.close('all')